# Generated by Django 3.0.3 on 2020-02-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.IntegerField(choices=[(1, 'HDB'), (2, 'Landed'), (3, 'Condominium')])),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Engaged'), (3, 'Married'), (4, 'Divorced')], default=1)),
                ('occupation_type', models.IntegerField(choices=[(1, 'Unemployed'), (2, 'Student'), (3, 'Employed')], default=1)),
                ('annual_income', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='household_search.Household')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household_search.FamilyMember')),
            ],
        ),
    ]
